### ISSUE TITLE
It doesnt work

### ISSUE THREAD

**Issue by zerealcrunch** [TermuxHackz/X-osint#13]
Traceback (most recent call last):
  File "/usr/local/bin/xosint", line 482, in <module>
    phone_info()
  File "/usr/local/bin/xosint", line 315, in phone_info
    print("\033[1;91m➤\033[1;97m Valid          : " + str(phe.json() ['valid']))
                                                          ~~~~~~~~~~^^^^^^^^^^
KeyError: 'valid'

**Comment by Justin-Lund** [comment]
I also get a key error "valid" when trying to do a phone number lookup on the Linux version, but on a different line #:

xosint>> 3
 [+] Enter phone number with country code: +13238941111

[+] Please enter a valid Opencage API key (Get from opencagedata.com): *****************************
[+] File written: ./opencage_api.txt

If you get an error it is likely due to the number of request going into the server so try again later

[~] Phone Number Details are given down below

➤ Target Number  : +13238941111
➤ Status Code    : 200
Traceback (most recent call last):
  File "/usr/local/bin/xosint", line 488, in <module>
    phone_info()
  File "/usr/local/bin/xosint", line 321, in phone_info
    print("\033[1;91m➤\033[1;97m Valid          : " + str(phe.json() ['valid']))
KeyError: 'valid'
parallels@parallels-Parallels-Virtual-Platform:~$

**Comment by TermuxHackz** [comment]
Hello @Justin-Lund , @zerealcrunch ,  kindly try again preferably after 24hrs, too many requests going through, I'm also working on another fix, thank you. It works on my side though, but thank you for opening an issue,
