### ISSUE TITLE
Movie Database OSINT option is shown as null

### ISSUE THREAD

**Issue by Tohka-aryani** [TermuxHackz/X-osint#19]
![image](https://github.com/TermuxHackz/X-osint/assets/129815399/015ce8de-7127-4b55-b63b-8a6bcc0a56f9)

Can't use the movie database option as the option returned as null.

**Comment by TermuxHackz** [comment]
Hello @Tohka-aryani , yes I'm well aware it is showing as null, cos the movie database isn't has been having some issues cos of the modules which have been deprecated. I'm working on another alternative so that's why the movie database is showing as null. Kindly use other features for now, thank you.
