### ISSUE TITLE
Don't start after install

### ISSUE THREAD

**Issue by DeFexCode** [TermuxHackz/X-osint#29]
Traceback (most recent call last):
  File "/data/data/com.termux/files/usr/bin/xosint", line 37, in <module>
    import folium
ModuleNotFoundError: No module named 'folium'
![Screenshot_20231031-105505219](https://github.com/TermuxHackz/X-osint/assets/143798005/18af1c94-1f87-4379-b145-d64874d63d50)

**Comment by Atuls-git** [comment]
@DeFexCode you can run it smoothly on kali linux, I've successfully ran & used it on my mobile running kali linux and didn't faced any issue, since Termux has been discontinued from last 2 years, the dependencies required to run this tools are not available and maintained now, so I suggest you to switch to Kali linux to run this wonderful tool, you can get Kali linux for your mobile [here](https://www.kali.org/get-kali/#kali-mobile)
